apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: my-mongodb
  template:
    metadata:
      labels:
        app: my-mongodb
    spec:
      containers:
      - name: my-container
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mongo_root_username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mongo_root_password
              
---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: my-mongodb
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
