apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongoexpress
spec:
  selector:
    matchLabels:
      app: my-mongdbexpress
  template:
    metadata:
      labels:
        app: my-mongodbexpress
    spec:
      containers:
      - name: my-expresscontainer
        image: mongo-express
        ports:
        - containerPort: 8081
        env:
        - name: MONGO_INITDB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mongo_root_username
        - name: MONGO_INITDB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: mongo_root_password
        - name: MONGO_INIT_ADMINsCONFIGMAP
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: mongo-service
              